add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[❯](bold #B565D8)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
style = "#B565D8"
repo_root_style = "bold #B565D8"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " 󰌾"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "italic #DA70D6"

[git_status]
format     = '[$all_status$ahead_behind]($style) '
style      = "#FF9F43"
ahead      = "⇡${count}"
diverged   = "⇕⇡${ahead_count}⇣${behind_count}"
behind     = "⇣${count}"
conflicted = "="
up_to_date = ""
untracked  = "?"
modified   = "!"
stashed    = "$"
staged     = "+"
renamed    = "»"
deleted    = "✗"
